// Code generated by `go generate`. DO NOT EDIT.
// source: server/internal/gen/hooks.go.tmpl
package mcp

import (
	"context"
)

// OnRegisterSessionHookFunc is a hook that will be called when a new session is registered.
type OnRegisterSessionHookFunc func(ctx context.Context, session ClientSession)

// OnUnregisterSessionHookFunc is a hook that will be called when a session is being unregistered.
type OnUnregisterSessionHookFunc func(ctx context.Context, session ClientSession)

// BeforeAnyHookFunc is a function that is called after the request is
// parsed but before the method is called.
type BeforeAnyHookFunc func(ctx context.Context, id any, method MCPMethod, message any)

// OnSuccessHookFunc is a hook that will be called after the request
// successfully generates a result, but before the result is sent to the 
type OnSuccessHookFunc func(ctx context.Context, id any, method MCPMethod, message any, result any)

// OnErrorHookFunc is a hook that will be called when an error occurs,
// either during the request parsing or the method execution.
//
// Example usage:
// ```
//
//	hooks.AddOnError(func(ctx context.Context, id any, method MCPMethod, message any, err error) {
//	  // Check for specific error types using errors.Is
//	  if errors.Is(err, ErrUnsupported) {
//	    // Handle capability not supported errors
//	    log.Printf("Capability not supported: %v", err)
//	  }
//
//	  // Use errors.As to get specific error types
//	  var parseErr = &UnparsableMessageError{}
//	  if errors.As(err, &parseErr) {
//	    // Access specific methods/fields of the error type
//	    log.Printf("Failed to parse message for method %s: %v",
//	               parseErr.GetMethod(), parseErr.Unwrap())
//	    // Access the raw message that failed to parse
//	    rawMsg := parseErr.GetMessage()
//	  }
//
//	  // Check for specific resource/prompt/tool errors
//	  switch {
//	  case errors.Is(err, ErrResourceNotFound):
//	    log.Printf("Resource not found: %v", err)
//	  case errors.Is(err, ErrPromptNotFound):
//	    log.Printf("Prompt not found: %v", err)
//	  case errors.Is(err, ErrToolNotFound):
//	    log.Printf("Tool not found: %v", err)
//	  }
//	})
type OnErrorHookFunc func(ctx context.Context, id any, method MCPMethod, message any, err error)

// OnRequestInitializationFunc is a function that called before handle diff request method
// Should any errors arise during func execution, the service will promptly return the corresponding error message.
type OnRequestInitializationFunc func(ctx context.Context, id any, message any) error

type OnBeforeInitializeFunc func(ctx context.Context, id any, message *InitializeRequest)
type OnAfterInitializeFunc func(ctx context.Context, id any, message *InitializeRequest, result *InitializeResult)

type OnBeforePingFunc func(ctx context.Context, id any, message *PingRequest)
type OnAfterPingFunc func(ctx context.Context, id any, message *PingRequest, result *EmptyResult)

type OnBeforeSetLevelFunc func(ctx context.Context, id any, message *SetLevelRequest)
type OnAfterSetLevelFunc func(ctx context.Context, id any, message *SetLevelRequest, result *EmptyResult)

type OnBeforeListResourcesFunc func(ctx context.Context, id any, message *ListResourcesRequest)
type OnAfterListResourcesFunc func(ctx context.Context, id any, message *ListResourcesRequest, result *ListResourcesResult)

type OnBeforeListResourceTemplatesFunc func(ctx context.Context, id any, message *ListResourceTemplatesRequest)
type OnAfterListResourceTemplatesFunc func(ctx context.Context, id any, message *ListResourceTemplatesRequest, result *ListResourceTemplatesResult)

type OnBeforeReadResourceFunc func(ctx context.Context, id any, message *ReadResourceRequest)
type OnAfterReadResourceFunc func(ctx context.Context, id any, message *ReadResourceRequest, result *ReadResourceResult)

type OnBeforeListPromptsFunc func(ctx context.Context, id any, message *ListPromptsRequest)
type OnAfterListPromptsFunc func(ctx context.Context, id any, message *ListPromptsRequest, result *ListPromptsResult)

type OnBeforeGetPromptFunc func(ctx context.Context, id any, message *GetPromptRequest)
type OnAfterGetPromptFunc func(ctx context.Context, id any, message *GetPromptRequest, result *GetPromptResult)

type OnBeforeListToolsFunc func(ctx context.Context, id any, message *ListToolsRequest)
type OnAfterListToolsFunc func(ctx context.Context, id any, message *ListToolsRequest, result *ListToolsResult)

type OnBeforeCallToolFunc func(ctx context.Context, id any, message *CallToolRequest)
type OnAfterCallToolFunc func(ctx context.Context, id any, message *CallToolRequest, result any)

type OnBeforeGetTaskFunc func(ctx context.Context, id any, message *GetTaskRequest)
type OnAfterGetTaskFunc func(ctx context.Context, id any, message *GetTaskRequest, result *GetTaskResult)

type OnBeforeListTasksFunc func(ctx context.Context, id any, message *ListTasksRequest)
type OnAfterListTasksFunc func(ctx context.Context, id any, message *ListTasksRequest, result *ListTasksResult)

type OnBeforeTaskResultFunc func(ctx context.Context, id any, message *TaskResultRequest)
type OnAfterTaskResultFunc func(ctx context.Context, id any, message *TaskResultRequest, result *TaskResultResult)

type OnBeforeCancelTaskFunc func(ctx context.Context, id any, message *CancelTaskRequest)
type OnAfterCancelTaskFunc func(ctx context.Context, id any, message *CancelTaskRequest, result *CancelTaskResult)

type OnBeforeCompleteFunc func(ctx context.Context, id any, message *CompleteRequest)
type OnAfterCompleteFunc func(ctx context.Context, id any, message *CompleteRequest, result *CompleteResult)

type Hooks struct {
	OnRegisterSession             []OnRegisterSessionHookFunc
	OnUnregisterSession           []OnUnregisterSessionHookFunc
	OnBeforeAny                   []BeforeAnyHookFunc
	OnSuccess                     []OnSuccessHookFunc
	OnError                       []OnErrorHookFunc
	OnRequestInitialization       []OnRequestInitializationFunc
	OnBeforeInitialize            []OnBeforeInitializeFunc
	OnAfterInitialize             []OnAfterInitializeFunc
	OnBeforePing                  []OnBeforePingFunc
	OnAfterPing                   []OnAfterPingFunc
	OnBeforeSetLevel              []OnBeforeSetLevelFunc
	OnAfterSetLevel               []OnAfterSetLevelFunc
	OnBeforeListResources         []OnBeforeListResourcesFunc
	OnAfterListResources          []OnAfterListResourcesFunc
	OnBeforeListResourceTemplates []OnBeforeListResourceTemplatesFunc
	OnAfterListResourceTemplates  []OnAfterListResourceTemplatesFunc
	OnBeforeReadResource          []OnBeforeReadResourceFunc
	OnAfterReadResource           []OnAfterReadResourceFunc
	OnBeforeListPrompts           []OnBeforeListPromptsFunc
	OnAfterListPrompts            []OnAfterListPromptsFunc
	OnBeforeGetPrompt             []OnBeforeGetPromptFunc
	OnAfterGetPrompt              []OnAfterGetPromptFunc
	OnBeforeListTools             []OnBeforeListToolsFunc
	OnAfterListTools              []OnAfterListToolsFunc
	OnBeforeCallTool              []OnBeforeCallToolFunc
	OnAfterCallTool               []OnAfterCallToolFunc
	OnBeforeGetTask               []OnBeforeGetTaskFunc
	OnAfterGetTask                []OnAfterGetTaskFunc
	OnBeforeListTasks             []OnBeforeListTasksFunc
	OnAfterListTasks              []OnAfterListTasksFunc
	OnBeforeTaskResult            []OnBeforeTaskResultFunc
	OnAfterTaskResult             []OnAfterTaskResultFunc
	OnBeforeCancelTask            []OnBeforeCancelTaskFunc
	OnAfterCancelTask             []OnAfterCancelTaskFunc
	OnBeforeComplete              []OnBeforeCompleteFunc
	OnAfterComplete               []OnAfterCompleteFunc
}

func (c *Hooks) AddBeforeAny(hook BeforeAnyHookFunc) {
	c.OnBeforeAny = append(c.OnBeforeAny, hook)
}

func (c *Hooks) AddOnSuccess(hook OnSuccessHookFunc) {
	c.OnSuccess = append(c.OnSuccess, hook)
}

// AddOnError registers a hook function that will be called when an error occurs.
// The error parameter contains the actual error object, which can be interrogated
// using Go's error handling patterns like errors.Is and errors.As.
//
// Example:
// ```
// // Create a channel to receive errors for testing
// errChan := make(chan error, 1)
//
// // Register hook to capture and inspect errors
// hooks := &Hooks{}
//
//	hooks.AddOnError(func(ctx context.Context, id any, method MCPMethod, message any, err error) {
//	    // For capability-related errors
//	    if errors.Is(err, ErrUnsupported) {
//	        // Handle capability not supported
//	        errChan <- err
//	        return
//	    }
//
//	    // For parsing errors
//	    var parseErr = &UnparsableMessageError{}
//	    if errors.As(err, &parseErr) {
//	        // Handle unparsable message errors
//	        fmt.Printf("Failed to parse %s request: %v\n",
//	                   parseErr.GetMethod(), parseErr.Unwrap())
//	        errChan <- parseErr
//	        return
//	    }
//
//	    // For resource/prompt/tool not found errors
//	    if errors.Is(err, ErrResourceNotFound) ||
//	       errors.Is(err, ErrPromptNotFound) ||
//	       errors.Is(err, ErrToolNotFound) {
//	        // Handle not found errors
//	        errChan <- err
//	        return
//	    }
//
//	    // For other errors
//	    errChan <- err
//	})
//
// server := NewMCPServer("test-server", "1.0.0", WithHooks(hooks))
// ```
func (c *Hooks) AddOnError(hook OnErrorHookFunc) {
	c.OnError = append(c.OnError, hook)
}

func (c *Hooks) beforeAny(ctx context.Context, id any, method MCPMethod, message any) {
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeAny {
		hook(ctx, id, method, message)
	}
}

func (c *Hooks) onSuccess(ctx context.Context, id any, method MCPMethod, message any, result any) {
	if c == nil {
		return
	}
	for _, hook := range c.OnSuccess {
		hook(ctx, id, method, message, result)
	}
}

// onError calls all registered error hooks with the error object.
// The err parameter contains the actual error that occurred, which implements
// the standard error interface and may be a wrapped error or custom error type.
//
// This allows consumer code to use Go's error handling patterns:
// - errors.Is(err, ErrUnsupported) to check for specific sentinel errors
// - errors.As(err, &customErr) to extract custom error types
//
// Common error types include:
// - ErrUnsupported: When a capability is not enabled
// - UnparsableMessageError: When request parsing fails
// - ErrResourceNotFound: When a resource is not found
// - ErrPromptNotFound: When a prompt is not found
// - ErrToolNotFound: When a tool is not found
func (c *Hooks) onError(ctx context.Context, id any, method MCPMethod, message any, err error) {
	if c == nil {
		return
	}
	for _, hook := range c.OnError {
		hook(ctx, id, method, message, err)
	}
}

func (c *Hooks) AddOnRegisterSession(hook OnRegisterSessionHookFunc) {
	c.OnRegisterSession = append(c.OnRegisterSession, hook)
}

func (c *Hooks) RegisterSession(ctx context.Context, session ClientSession) {
	if c == nil {
		return
	}
	for _, hook := range c.OnRegisterSession {
		hook(ctx, session)
	}
}

func (c *Hooks) AddOnUnregisterSession(hook OnUnregisterSessionHookFunc) {
	c.OnUnregisterSession = append(c.OnUnregisterSession, hook)
}

func (c *Hooks) UnregisterSession(ctx context.Context, session ClientSession) {
	if c == nil {
		return
	}
	for _, hook := range c.OnUnregisterSession {
		hook(ctx, session)
	}
}

func (c *Hooks) AddOnRequestInitialization(hook OnRequestInitializationFunc) {
	c.OnRequestInitialization = append(c.OnRequestInitialization, hook)
}

func (c *Hooks) onRequestInitialization(ctx context.Context, id any, message any) error {
	if c == nil {
		return nil
	}
	for _, hook := range c.OnRequestInitialization {
		err := hook(ctx, id, message)
		if err != nil {
			return err
		}
	}
	return nil
}
func (c *Hooks) AddBeforeInitialize(hook OnBeforeInitializeFunc) {
	c.OnBeforeInitialize = append(c.OnBeforeInitialize, hook)
}

func (c *Hooks) AddAfterInitialize(hook OnAfterInitializeFunc) {
	c.OnAfterInitialize = append(c.OnAfterInitialize, hook)
}

func (c *Hooks) beforeInitialize(ctx context.Context, id any, message *InitializeRequest) {
	c.beforeAny(ctx, id, MethodInitialize, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeInitialize {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterInitialize(ctx context.Context, id any, message *InitializeRequest, result *InitializeResult) {
	c.onSuccess(ctx, id, MethodInitialize, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterInitialize {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforePing(hook OnBeforePingFunc) {
	c.OnBeforePing = append(c.OnBeforePing, hook)
}

func (c *Hooks) AddAfterPing(hook OnAfterPingFunc) {
	c.OnAfterPing = append(c.OnAfterPing, hook)
}

func (c *Hooks) beforePing(ctx context.Context, id any, message *PingRequest) {
	c.beforeAny(ctx, id, MethodPing, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforePing {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterPing(ctx context.Context, id any, message *PingRequest, result *EmptyResult) {
	c.onSuccess(ctx, id, MethodPing, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterPing {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforeSetLevel(hook OnBeforeSetLevelFunc) {
	c.OnBeforeSetLevel = append(c.OnBeforeSetLevel, hook)
}

func (c *Hooks) AddAfterSetLevel(hook OnAfterSetLevelFunc) {
	c.OnAfterSetLevel = append(c.OnAfterSetLevel, hook)
}

func (c *Hooks) beforeSetLevel(ctx context.Context, id any, message *SetLevelRequest) {
	c.beforeAny(ctx, id, MethodSetLogLevel, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeSetLevel {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterSetLevel(ctx context.Context, id any, message *SetLevelRequest, result *EmptyResult) {
	c.onSuccess(ctx, id, MethodSetLogLevel, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterSetLevel {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforeListResources(hook OnBeforeListResourcesFunc) {
	c.OnBeforeListResources = append(c.OnBeforeListResources, hook)
}

func (c *Hooks) AddAfterListResources(hook OnAfterListResourcesFunc) {
	c.OnAfterListResources = append(c.OnAfterListResources, hook)
}

func (c *Hooks) beforeListResources(ctx context.Context, id any, message *ListResourcesRequest) {
	c.beforeAny(ctx, id, MethodResourcesList, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeListResources {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterListResources(ctx context.Context, id any, message *ListResourcesRequest, result *ListResourcesResult) {
	c.onSuccess(ctx, id, MethodResourcesList, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterListResources {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforeListResourceTemplates(hook OnBeforeListResourceTemplatesFunc) {
	c.OnBeforeListResourceTemplates = append(c.OnBeforeListResourceTemplates, hook)
}

func (c *Hooks) AddAfterListResourceTemplates(hook OnAfterListResourceTemplatesFunc) {
	c.OnAfterListResourceTemplates = append(c.OnAfterListResourceTemplates, hook)
}

func (c *Hooks) beforeListResourceTemplates(ctx context.Context, id any, message *ListResourceTemplatesRequest) {
	c.beforeAny(ctx, id, MethodResourcesTemplatesList, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeListResourceTemplates {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterListResourceTemplates(ctx context.Context, id any, message *ListResourceTemplatesRequest, result *ListResourceTemplatesResult) {
	c.onSuccess(ctx, id, MethodResourcesTemplatesList, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterListResourceTemplates {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforeReadResource(hook OnBeforeReadResourceFunc) {
	c.OnBeforeReadResource = append(c.OnBeforeReadResource, hook)
}

func (c *Hooks) AddAfterReadResource(hook OnAfterReadResourceFunc) {
	c.OnAfterReadResource = append(c.OnAfterReadResource, hook)
}

func (c *Hooks) beforeReadResource(ctx context.Context, id any, message *ReadResourceRequest) {
	c.beforeAny(ctx, id, MethodResourcesRead, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeReadResource {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterReadResource(ctx context.Context, id any, message *ReadResourceRequest, result *ReadResourceResult) {
	c.onSuccess(ctx, id, MethodResourcesRead, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterReadResource {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforeListPrompts(hook OnBeforeListPromptsFunc) {
	c.OnBeforeListPrompts = append(c.OnBeforeListPrompts, hook)
}

func (c *Hooks) AddAfterListPrompts(hook OnAfterListPromptsFunc) {
	c.OnAfterListPrompts = append(c.OnAfterListPrompts, hook)
}

func (c *Hooks) beforeListPrompts(ctx context.Context, id any, message *ListPromptsRequest) {
	c.beforeAny(ctx, id, MethodPromptsList, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeListPrompts {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterListPrompts(ctx context.Context, id any, message *ListPromptsRequest, result *ListPromptsResult) {
	c.onSuccess(ctx, id, MethodPromptsList, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterListPrompts {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforeGetPrompt(hook OnBeforeGetPromptFunc) {
	c.OnBeforeGetPrompt = append(c.OnBeforeGetPrompt, hook)
}

func (c *Hooks) AddAfterGetPrompt(hook OnAfterGetPromptFunc) {
	c.OnAfterGetPrompt = append(c.OnAfterGetPrompt, hook)
}

func (c *Hooks) beforeGetPrompt(ctx context.Context, id any, message *GetPromptRequest) {
	c.beforeAny(ctx, id, MethodPromptsGet, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeGetPrompt {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterGetPrompt(ctx context.Context, id any, message *GetPromptRequest, result *GetPromptResult) {
	c.onSuccess(ctx, id, MethodPromptsGet, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterGetPrompt {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforeListTools(hook OnBeforeListToolsFunc) {
	c.OnBeforeListTools = append(c.OnBeforeListTools, hook)
}

func (c *Hooks) AddAfterListTools(hook OnAfterListToolsFunc) {
	c.OnAfterListTools = append(c.OnAfterListTools, hook)
}

func (c *Hooks) beforeListTools(ctx context.Context, id any, message *ListToolsRequest) {
	c.beforeAny(ctx, id, MethodToolsList, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeListTools {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterListTools(ctx context.Context, id any, message *ListToolsRequest, result *ListToolsResult) {
	c.onSuccess(ctx, id, MethodToolsList, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterListTools {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforeCallTool(hook OnBeforeCallToolFunc) {
	c.OnBeforeCallTool = append(c.OnBeforeCallTool, hook)
}

func (c *Hooks) AddAfterCallTool(hook OnAfterCallToolFunc) {
	c.OnAfterCallTool = append(c.OnAfterCallTool, hook)
}

func (c *Hooks) beforeCallTool(ctx context.Context, id any, message *CallToolRequest) {
	c.beforeAny(ctx, id, MethodToolsCall, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeCallTool {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterCallTool(ctx context.Context, id any, message *CallToolRequest, result any) {
	c.onSuccess(ctx, id, MethodToolsCall, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterCallTool {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforeGetTask(hook OnBeforeGetTaskFunc) {
	c.OnBeforeGetTask = append(c.OnBeforeGetTask, hook)
}

func (c *Hooks) AddAfterGetTask(hook OnAfterGetTaskFunc) {
	c.OnAfterGetTask = append(c.OnAfterGetTask, hook)
}

func (c *Hooks) beforeGetTask(ctx context.Context, id any, message *GetTaskRequest) {
	c.beforeAny(ctx, id, MethodTasksGet, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeGetTask {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterGetTask(ctx context.Context, id any, message *GetTaskRequest, result *GetTaskResult) {
	c.onSuccess(ctx, id, MethodTasksGet, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterGetTask {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforeListTasks(hook OnBeforeListTasksFunc) {
	c.OnBeforeListTasks = append(c.OnBeforeListTasks, hook)
}

func (c *Hooks) AddAfterListTasks(hook OnAfterListTasksFunc) {
	c.OnAfterListTasks = append(c.OnAfterListTasks, hook)
}

func (c *Hooks) beforeListTasks(ctx context.Context, id any, message *ListTasksRequest) {
	c.beforeAny(ctx, id, MethodTasksList, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeListTasks {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterListTasks(ctx context.Context, id any, message *ListTasksRequest, result *ListTasksResult) {
	c.onSuccess(ctx, id, MethodTasksList, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterListTasks {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforeTaskResult(hook OnBeforeTaskResultFunc) {
	c.OnBeforeTaskResult = append(c.OnBeforeTaskResult, hook)
}

func (c *Hooks) AddAfterTaskResult(hook OnAfterTaskResultFunc) {
	c.OnAfterTaskResult = append(c.OnAfterTaskResult, hook)
}

func (c *Hooks) beforeTaskResult(ctx context.Context, id any, message *TaskResultRequest) {
	c.beforeAny(ctx, id, MethodTasksResult, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeTaskResult {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterTaskResult(ctx context.Context, id any, message *TaskResultRequest, result *TaskResultResult) {
	c.onSuccess(ctx, id, MethodTasksResult, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterTaskResult {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforeCancelTask(hook OnBeforeCancelTaskFunc) {
	c.OnBeforeCancelTask = append(c.OnBeforeCancelTask, hook)
}

func (c *Hooks) AddAfterCancelTask(hook OnAfterCancelTaskFunc) {
	c.OnAfterCancelTask = append(c.OnAfterCancelTask, hook)
}

func (c *Hooks) beforeCancelTask(ctx context.Context, id any, message *CancelTaskRequest) {
	c.beforeAny(ctx, id, MethodTasksCancel, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeCancelTask {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterCancelTask(ctx context.Context, id any, message *CancelTaskRequest, result *CancelTaskResult) {
	c.onSuccess(ctx, id, MethodTasksCancel, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterCancelTask {
		hook(ctx, id, message, result)
	}
}
func (c *Hooks) AddBeforeComplete(hook OnBeforeCompleteFunc) {
	c.OnBeforeComplete = append(c.OnBeforeComplete, hook)
}

func (c *Hooks) AddAfterComplete(hook OnAfterCompleteFunc) {
	c.OnAfterComplete = append(c.OnAfterComplete, hook)
}

func (c *Hooks) beforeComplete(ctx context.Context, id any, message *CompleteRequest) {
	c.beforeAny(ctx, id, MethodCompletionComplete, message)
	if c == nil {
		return
	}
	for _, hook := range c.OnBeforeComplete {
		hook(ctx, id, message)
	}
}

func (c *Hooks) afterComplete(ctx context.Context, id any, message *CompleteRequest, result *CompleteResult) {
	c.onSuccess(ctx, id, MethodCompletionComplete, message, result)
	if c == nil {
		return
	}
	for _, hook := range c.OnAfterComplete {
		hook(ctx, id, message, result)
	}
}
