// DO NOT EDIT. generated by github.com/tinywasm/orm

package mcp

import (
	"github.com/tinywasm/fmt"
)

func (m *rpcRequest) FormName() string {
	return "rpc_request"
}

var _schemarpcRequest = []fmt.Field{
		{Name: "jsonrpc", Type: fmt.FieldText, JSON: "jsonrpc"},
		{Name: "id", Type: fmt.FieldInt, PK: true, JSON: "id"},
		{Name: "method", Type: fmt.FieldText, JSON: "method"},
		{Name: "params", Type: fmt.FieldText, JSON: "params"},
	}

func (m *rpcRequest) Schema() []fmt.Field { return _schemarpcRequest }

func (m *rpcRequest) Pointers() []any {
	return []any{
		&m.JSONRPC,
		&m.ID,
		&m.Method,
		&m.Params,
	}
}

func (m *rpcResponse) FormName() string {
	return "rpc_response"
}

var _schemarpcResponse = []fmt.Field{
		{Name: "result", Type: fmt.FieldText, JSON: "result"},
	}

func (m *rpcResponse) Schema() []fmt.Field { return _schemarpcResponse }

func (m *rpcResponse) Pointers() []any {
	return []any{
		&m.Result,
	}
}
