// DO NOT EDIT. generated by github.com/tinywasm/orm

package mcp

import (
	"github.com/tinywasm/model"
)

func (m *rpcRequest) ModelName() string {
	return "rpc_request"
}

var _schemarpcRequest = []model.Field{
		{Name: "jsonrpc", Type: model.FieldText},
		{Name: "id", Type: model.FieldText},
		{Name: "method", Type: model.FieldText},
		{Name: "params", Type: model.FieldText},
	}

func (m *rpcRequest) Schema() []model.Field { return _schemarpcRequest }

func (m *rpcRequest) Pointers() []any { return []any{&m.JSONRPC, &m.ID, &m.Method, &m.Params} }

func (m *rpcRequest) IsNil() bool { return m == nil }

func (m *rpcRequest) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.JSONRPC)
	w.String("id", m.ID)
	w.String("method", m.Method)
	w.String("params", m.Params)
}

func (m *rpcRequest) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.JSONRPC = v }
	if v, ok := r.String("id"); ok { m.ID = v }
	if v, ok := r.String("method"); ok { m.Method = v }
	if v, ok := r.String("params"); ok { m.Params = v }
}

type rpcRequestList []*rpcRequest

func (s *rpcRequestList) Schema() []model.Field { return nil }
func (s *rpcRequestList) Pointers() []any     { return nil }
func (s *rpcRequestList) Len() int             { return len(*s) }
func (s *rpcRequestList) At(i int) model.Fielder { return (*s)[i] }
func (s *rpcRequestList) Append() model.Fielder  { v := &rpcRequest{}; *s = append(*s, v); return v }
func (s *rpcRequestList) IsNil() bool          { return s == nil }
func (s *rpcRequestList) EncodeFields(_ model.FieldWriter) {}
func (s *rpcRequestList) DecodeFields(_ model.FieldReader) {}

func (m *rpcResponse) ModelName() string {
	return "rpc_response"
}

var _schemarpcResponse = []model.Field{
		{Name: "jsonrpc", Type: model.FieldText},
		{Name: "id", Type: model.FieldText},
		{Name: "result", Type: model.FieldRaw, OmitEmpty: true},
		{Name: "error", Type: model.FieldText, OmitEmpty: true},
	}

func (m *rpcResponse) Schema() []model.Field { return _schemarpcResponse }

func (m *rpcResponse) Pointers() []any { return []any{&m.JSONRPC, &m.ID, &m.Result, &m.Error} }

func (m *rpcResponse) IsNil() bool { return m == nil }

func (m *rpcResponse) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.JSONRPC)
	w.String("id", m.ID)
	if len(m.Result) != 0 { w.Raw("result", m.Result) }
	if m.Error != "" { w.String("error", m.Error) }
}

func (m *rpcResponse) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.JSONRPC = v }
	if v, ok := r.String("id"); ok { m.ID = v }
	if v, ok := r.Raw("result"); ok { m.Result = v }
	if v, ok := r.String("error"); ok { m.Error = v }
}

type rpcResponseList []*rpcResponse

func (s *rpcResponseList) Schema() []model.Field { return nil }
func (s *rpcResponseList) Pointers() []any     { return nil }
func (s *rpcResponseList) Len() int             { return len(*s) }
func (s *rpcResponseList) At(i int) model.Fielder { return (*s)[i] }
func (s *rpcResponseList) Append() model.Fielder  { v := &rpcResponse{}; *s = append(*s, v); return v }
func (s *rpcResponseList) IsNil() bool          { return s == nil }
func (s *rpcResponseList) EncodeFields(_ model.FieldWriter) {}
func (s *rpcResponseList) DecodeFields(_ model.FieldReader) {}

func (m *jsonRPCError) ModelName() string {
	return "json_rpcerror"
}

var _schemajsonRPCError = []model.Field{
		{Name: "code", Type: model.FieldInt},
		{Name: "message", Type: model.FieldText},
		{Name: "data", Type: model.FieldText, OmitEmpty: true},
	}

func (m *jsonRPCError) Schema() []model.Field { return _schemajsonRPCError }

func (m *jsonRPCError) Pointers() []any { return []any{&m.Code, &m.Message, &m.Data} }

func (m *jsonRPCError) IsNil() bool { return m == nil }

func (m *jsonRPCError) EncodeFields(w model.FieldWriter) {
	w.Int("code", int64(m.Code))
	w.String("message", m.Message)
	if m.Data != "" { w.String("data", m.Data) }
}

func (m *jsonRPCError) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("code"); ok { m.Code = int64(v) }
	if v, ok := r.String("message"); ok { m.Message = v }
	if v, ok := r.String("data"); ok { m.Data = v }
}

type jsonRPCErrorList []*jsonRPCError

func (s *jsonRPCErrorList) Schema() []model.Field { return nil }
func (s *jsonRPCErrorList) Pointers() []any     { return nil }
func (s *jsonRPCErrorList) Len() int             { return len(*s) }
func (s *jsonRPCErrorList) At(i int) model.Fielder { return (*s)[i] }
func (s *jsonRPCErrorList) Append() model.Fielder  { v := &jsonRPCError{}; *s = append(*s, v); return v }
func (s *jsonRPCErrorList) IsNil() bool          { return s == nil }
func (s *jsonRPCErrorList) EncodeFields(_ model.FieldWriter) {}
func (s *jsonRPCErrorList) DecodeFields(_ model.FieldReader) {}

func (m *initializeParams) ModelName() string {
	return "initialize_params"
}

var _schemainitializeParams = []model.Field{
		{Name: "protocolVersion", Type: model.FieldText},
		{Name: "clientInfo", Type: model.FieldStruct},
	}

func (m *initializeParams) Schema() []model.Field { return _schemainitializeParams }

func (m *initializeParams) Pointers() []any { return []any{&m.ProtocolVersion, &m.ClientInfo} }

func (m *initializeParams) IsNil() bool { return m == nil }

func (m *initializeParams) EncodeFields(w model.FieldWriter) {
	w.String("protocolVersion", m.ProtocolVersion)
	w.Object("clientInfo", &m.ClientInfo)
}

func (m *initializeParams) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("protocolVersion"); ok { m.ProtocolVersion = v }
	r.Object("clientInfo", &m.ClientInfo)
}

type initializeParamsList []*initializeParams

func (s *initializeParamsList) Schema() []model.Field { return nil }
func (s *initializeParamsList) Pointers() []any     { return nil }
func (s *initializeParamsList) Len() int             { return len(*s) }
func (s *initializeParamsList) At(i int) model.Fielder { return (*s)[i] }
func (s *initializeParamsList) Append() model.Fielder  { v := &initializeParams{}; *s = append(*s, v); return v }
func (s *initializeParamsList) IsNil() bool          { return s == nil }
func (s *initializeParamsList) EncodeFields(_ model.FieldWriter) {}
func (s *initializeParamsList) DecodeFields(_ model.FieldReader) {}

func (m *implementationInfo) ModelName() string {
	return "implementation_info"
}

var _schemaimplementationInfo = []model.Field{
		{Name: "name", Type: model.FieldText},
		{Name: "version", Type: model.FieldText},
	}

func (m *implementationInfo) Schema() []model.Field { return _schemaimplementationInfo }

func (m *implementationInfo) Pointers() []any { return []any{&m.Name, &m.Version} }

func (m *implementationInfo) IsNil() bool { return m == nil }

func (m *implementationInfo) EncodeFields(w model.FieldWriter) {
	w.String("name", m.Name)
	w.String("version", m.Version)
}

func (m *implementationInfo) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("version"); ok { m.Version = v }
}

type implementationInfoList []*implementationInfo

func (s *implementationInfoList) Schema() []model.Field { return nil }
func (s *implementationInfoList) Pointers() []any     { return nil }
func (s *implementationInfoList) Len() int             { return len(*s) }
func (s *implementationInfoList) At(i int) model.Fielder { return (*s)[i] }
func (s *implementationInfoList) Append() model.Fielder  { v := &implementationInfo{}; *s = append(*s, v); return v }
func (s *implementationInfoList) IsNil() bool          { return s == nil }
func (s *implementationInfoList) EncodeFields(_ model.FieldWriter) {}
func (s *implementationInfoList) DecodeFields(_ model.FieldReader) {}

func (m *initializeResult) ModelName() string {
	return "initialize_result"
}

var _schemainitializeResult = []model.Field{
		{Name: "protocolVersion", Type: model.FieldText},
		{Name: "serverInfo", Type: model.FieldStruct},
		{Name: "capabilities", Type: model.FieldRaw, OmitEmpty: true},
	}

func (m *initializeResult) Schema() []model.Field { return _schemainitializeResult }

func (m *initializeResult) Pointers() []any { return []any{&m.ProtocolVersion, &m.ServerInfo, &m.Capabilities} }

func (m *initializeResult) IsNil() bool { return m == nil }

func (m *initializeResult) EncodeFields(w model.FieldWriter) {
	w.String("protocolVersion", m.ProtocolVersion)
	w.Object("serverInfo", &m.ServerInfo)
	if len(m.Capabilities) != 0 { w.Raw("capabilities", m.Capabilities) }
}

func (m *initializeResult) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("protocolVersion"); ok { m.ProtocolVersion = v }
	r.Object("serverInfo", &m.ServerInfo)
	if v, ok := r.Raw("capabilities"); ok { m.Capabilities = v }
}

type initializeResultList []*initializeResult

func (s *initializeResultList) Schema() []model.Field { return nil }
func (s *initializeResultList) Pointers() []any     { return nil }
func (s *initializeResultList) Len() int             { return len(*s) }
func (s *initializeResultList) At(i int) model.Fielder { return (*s)[i] }
func (s *initializeResultList) Append() model.Fielder  { v := &initializeResult{}; *s = append(*s, v); return v }
func (s *initializeResultList) IsNil() bool          { return s == nil }
func (s *initializeResultList) EncodeFields(_ model.FieldWriter) {}
func (s *initializeResultList) DecodeFields(_ model.FieldReader) {}

func (m *CallToolParams) ModelName() string {
	return "call_tool_params"
}

var _schemaCallToolParams = []model.Field{
		{Name: "name", Type: model.FieldText},
		{Name: "arguments", Type: model.FieldRaw},
	}

func (m *CallToolParams) Schema() []model.Field { return _schemaCallToolParams }

func (m *CallToolParams) Pointers() []any { return []any{&m.Name, &m.Arguments} }

func (m *CallToolParams) IsNil() bool { return m == nil }

func (m *CallToolParams) EncodeFields(w model.FieldWriter) {
	w.String("name", m.Name)
	w.Raw("arguments", m.Arguments)
}

func (m *CallToolParams) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.Raw("arguments"); ok { m.Arguments = v }
}

type CallToolParamsList []*CallToolParams

func (s *CallToolParamsList) Schema() []model.Field { return nil }
func (s *CallToolParamsList) Pointers() []any     { return nil }
func (s *CallToolParamsList) Len() int             { return len(*s) }
func (s *CallToolParamsList) At(i int) model.Fielder { return (*s)[i] }
func (s *CallToolParamsList) Append() model.Fielder  { v := &CallToolParams{}; *s = append(*s, v); return v }
func (s *CallToolParamsList) IsNil() bool          { return s == nil }
func (s *CallToolParamsList) EncodeFields(_ model.FieldWriter) {}
func (s *CallToolParamsList) DecodeFields(_ model.FieldReader) {}

func (m *Result) ModelName() string {
	return "result"
}

var _schemaResult = []model.Field{
		{Name: "isError", Type: model.FieldBool, OmitEmpty: true},
		{Name: "content", Type: model.FieldRaw, OmitEmpty: true},
	}

func (m *Result) Schema() []model.Field { return _schemaResult }

func (m *Result) Pointers() []any { return []any{&m.IsError, &m.Content} }

func (m *Result) IsNil() bool { return m == nil }

func (m *Result) EncodeFields(w model.FieldWriter) {
	if m.IsError { w.Bool("isError", m.IsError) }
	if len(m.Content) != 0 { w.Raw("content", m.Content) }
}

func (m *Result) DecodeFields(r model.FieldReader) {
	if v, ok := r.Bool("isError"); ok { m.IsError = v }
	if v, ok := r.Raw("content"); ok { m.Content = v }
}

type ResultList []*Result

func (s *ResultList) Schema() []model.Field { return nil }
func (s *ResultList) Pointers() []any     { return nil }
func (s *ResultList) Len() int             { return len(*s) }
func (s *ResultList) At(i int) model.Fielder { return (*s)[i] }
func (s *ResultList) Append() model.Fielder  { v := &Result{}; *s = append(*s, v); return v }
func (s *ResultList) IsNil() bool          { return s == nil }
func (s *ResultList) EncodeFields(_ model.FieldWriter) {}
func (s *ResultList) DecodeFields(_ model.FieldReader) {}

func (m *TextContent) ModelName() string {
	return "text_content"
}

var _schemaTextContent = []model.Field{
		{Name: "type", Type: model.FieldText},
		{Name: "text", Type: model.FieldText},
	}

func (m *TextContent) Schema() []model.Field { return _schemaTextContent }

func (m *TextContent) Pointers() []any { return []any{&m.Type, &m.Text} }

func (m *TextContent) IsNil() bool { return m == nil }

func (m *TextContent) EncodeFields(w model.FieldWriter) {
	w.String("type", m.Type)
	w.String("text", m.Text)
}

func (m *TextContent) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("type"); ok { m.Type = v }
	if v, ok := r.String("text"); ok { m.Text = v }
}

type TextContentList []*TextContent

func (s *TextContentList) Schema() []model.Field { return nil }
func (s *TextContentList) Pointers() []any     { return nil }
func (s *TextContentList) Len() int             { return len(*s) }
func (s *TextContentList) At(i int) model.Fielder { return (*s)[i] }
func (s *TextContentList) Append() model.Fielder  { v := &TextContent{}; *s = append(*s, v); return v }
func (s *TextContentList) IsNil() bool          { return s == nil }
func (s *TextContentList) EncodeFields(_ model.FieldWriter) {}
func (s *TextContentList) DecodeFields(_ model.FieldReader) {}

func (m *toolEntry) ModelName() string {
	return "tool_entry"
}

var _schematoolEntry = []model.Field{
		{Name: "name", Type: model.FieldText},
		{Name: "description", Type: model.FieldText, OmitEmpty: true},
		{Name: "inputSchema", Type: model.FieldRaw},
	}

func (m *toolEntry) Schema() []model.Field { return _schematoolEntry }

func (m *toolEntry) Pointers() []any { return []any{&m.Name, &m.Description, &m.InputSchema} }

func (m *toolEntry) IsNil() bool { return m == nil }

func (m *toolEntry) EncodeFields(w model.FieldWriter) {
	w.String("name", m.Name)
	if m.Description != "" { w.String("description", m.Description) }
	w.Raw("inputSchema", m.InputSchema)
}

func (m *toolEntry) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("description"); ok { m.Description = v }
	if v, ok := r.Raw("inputSchema"); ok { m.InputSchema = v }
}

type toolEntryList []*toolEntry

func (s *toolEntryList) Schema() []model.Field { return nil }
func (s *toolEntryList) Pointers() []any     { return nil }
func (s *toolEntryList) Len() int             { return len(*s) }
func (s *toolEntryList) At(i int) model.Fielder { return (*s)[i] }
func (s *toolEntryList) Append() model.Fielder  { v := &toolEntry{}; *s = append(*s, v); return v }
func (s *toolEntryList) IsNil() bool          { return s == nil }
func (s *toolEntryList) EncodeFields(_ model.FieldWriter) {}
func (s *toolEntryList) DecodeFields(_ model.FieldReader) {}

func (m *listToolsResult) ModelName() string {
	return "list_tools_result"
}

var _schemalistToolsResult = []model.Field{
		{Name: "tools", Type: model.FieldRaw},
		{Name: "nextCursor", Type: model.FieldText, OmitEmpty: true},
	}

func (m *listToolsResult) Schema() []model.Field { return _schemalistToolsResult }

func (m *listToolsResult) Pointers() []any { return []any{&m.Tools, &m.NextCursor} }

func (m *listToolsResult) IsNil() bool { return m == nil }

func (m *listToolsResult) EncodeFields(w model.FieldWriter) {
	w.Raw("tools", m.Tools)
	if m.NextCursor != "" { w.String("nextCursor", m.NextCursor) }
}

func (m *listToolsResult) DecodeFields(r model.FieldReader) {
	if v, ok := r.Raw("tools"); ok { m.Tools = v }
	if v, ok := r.String("nextCursor"); ok { m.NextCursor = v }
}

type listToolsResultList []*listToolsResult

func (s *listToolsResultList) Schema() []model.Field { return nil }
func (s *listToolsResultList) Pointers() []any     { return nil }
func (s *listToolsResultList) Len() int             { return len(*s) }
func (s *listToolsResultList) At(i int) model.Fielder { return (*s)[i] }
func (s *listToolsResultList) Append() model.Fielder  { v := &listToolsResult{}; *s = append(*s, v); return v }
func (s *listToolsResultList) IsNil() bool          { return s == nil }
func (s *listToolsResultList) EncodeFields(_ model.FieldWriter) {}
func (s *listToolsResultList) DecodeFields(_ model.FieldReader) {}

func (m *errorResponse) ModelName() string {
	return "error_response"
}

var _schemaerrorResponse = []model.Field{
		{Name: "jsonrpc", Type: model.FieldText},
		{Name: "id", Type: model.FieldText, OmitEmpty: true},
		{Name: "error", Type: model.FieldStruct},
	}

func (m *errorResponse) Schema() []model.Field { return _schemaerrorResponse }

func (m *errorResponse) Pointers() []any { return []any{&m.JSONRPC, &m.ID, &m.Error} }

func (m *errorResponse) IsNil() bool { return m == nil }

func (m *errorResponse) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.JSONRPC)
	if m.ID != "" { w.String("id", m.ID) }
	w.Object("error", &m.Error)
}

func (m *errorResponse) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.JSONRPC = v }
	if v, ok := r.String("id"); ok { m.ID = v }
	r.Object("error", &m.Error)
}

type errorResponseList []*errorResponse

func (s *errorResponseList) Schema() []model.Field { return nil }
func (s *errorResponseList) Pointers() []any     { return nil }
func (s *errorResponseList) Len() int             { return len(*s) }
func (s *errorResponseList) At(i int) model.Fielder { return (*s)[i] }
func (s *errorResponseList) Append() model.Fielder  { v := &errorResponse{}; *s = append(*s, v); return v }
func (s *errorResponseList) IsNil() bool          { return s == nil }
func (s *errorResponseList) EncodeFields(_ model.FieldWriter) {}
func (s *errorResponseList) DecodeFields(_ model.FieldReader) {}

func (m *Meta) ModelName() string {
	return "meta"
}

var _schemaMeta = []model.Field{
		{Name: "progressToken", Type: model.FieldText, OmitEmpty: true},
	}

func (m *Meta) Schema() []model.Field { return _schemaMeta }

func (m *Meta) Pointers() []any { return []any{&m.ProgressToken} }

func (m *Meta) IsNil() bool { return m == nil }

func (m *Meta) EncodeFields(w model.FieldWriter) {
	if m.ProgressToken != "" { w.String("progressToken", m.ProgressToken) }
}

func (m *Meta) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("progressToken"); ok { m.ProgressToken = v }
}

type MetaList []*Meta

func (s *MetaList) Schema() []model.Field { return nil }
func (s *MetaList) Pointers() []any     { return nil }
func (s *MetaList) Len() int             { return len(*s) }
func (s *MetaList) At(i int) model.Fielder { return (*s)[i] }
func (s *MetaList) Append() model.Fielder  { v := &Meta{}; *s = append(*s, v); return v }
func (s *MetaList) IsNil() bool          { return s == nil }
func (s *MetaList) EncodeFields(_ model.FieldWriter) {}
func (s *MetaList) DecodeFields(_ model.FieldReader) {}

func (m *NotificationParams) ModelName() string {
	return "notification_params"
}

var _schemaNotificationParams = []model.Field{
		{Name: "meta", Type: model.FieldText, OmitEmpty: true},
	}

func (m *NotificationParams) Schema() []model.Field { return _schemaNotificationParams }

func (m *NotificationParams) Pointers() []any { return []any{&m.Meta} }

func (m *NotificationParams) IsNil() bool { return m == nil }

func (m *NotificationParams) EncodeFields(w model.FieldWriter) {
	if m.Meta != "" { w.String("meta", m.Meta) }
}

func (m *NotificationParams) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("meta"); ok { m.Meta = v }
}

type NotificationParamsList []*NotificationParams

func (s *NotificationParamsList) Schema() []model.Field { return nil }
func (s *NotificationParamsList) Pointers() []any     { return nil }
func (s *NotificationParamsList) Len() int             { return len(*s) }
func (s *NotificationParamsList) At(i int) model.Fielder { return (*s)[i] }
func (s *NotificationParamsList) Append() model.Fielder  { v := &NotificationParams{}; *s = append(*s, v); return v }
func (s *NotificationParamsList) IsNil() bool          { return s == nil }
func (s *NotificationParamsList) EncodeFields(_ model.FieldWriter) {}
func (s *NotificationParamsList) DecodeFields(_ model.FieldReader) {}

func (m *EmptyResult) ModelName() string {
	return "empty_result"
}

var _schemaEmptyResult = []model.Field{
		{Name: "result", Type: model.FieldText, OmitEmpty: true},
	}

func (m *EmptyResult) Schema() []model.Field { return _schemaEmptyResult }

func (m *EmptyResult) Pointers() []any { return []any{&m.Result} }

func (m *EmptyResult) IsNil() bool { return m == nil }

func (m *EmptyResult) EncodeFields(w model.FieldWriter) {
	if m.Result != "" { w.String("result", m.Result) }
}

func (m *EmptyResult) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("result"); ok { m.Result = v }
}

type EmptyResultList []*EmptyResult

func (s *EmptyResultList) Schema() []model.Field { return nil }
func (s *EmptyResultList) Pointers() []any     { return nil }
func (s *EmptyResultList) Len() int             { return len(*s) }
func (s *EmptyResultList) At(i int) model.Fielder { return (*s)[i] }
func (s *EmptyResultList) Append() model.Fielder  { v := &EmptyResult{}; *s = append(*s, v); return v }
func (s *EmptyResultList) IsNil() bool          { return s == nil }
func (s *EmptyResultList) EncodeFields(_ model.FieldWriter) {}
func (s *EmptyResultList) DecodeFields(_ model.FieldReader) {}

func (m *JSONRPCRequest) ModelName() string {
	return "jsonrpcrequest"
}

var _schemaJSONRPCRequest = []model.Field{
		{Name: "jsonrpc", Type: model.FieldText},
		{Name: "id", Type: model.FieldText},
		{Name: "method", Type: model.FieldText},
		{Name: "params", Type: model.FieldText, OmitEmpty: true},
	}

func (m *JSONRPCRequest) Schema() []model.Field { return _schemaJSONRPCRequest }

func (m *JSONRPCRequest) Pointers() []any { return []any{&m.JSONRPC, &m.ID, &m.Method, &m.Params} }

func (m *JSONRPCRequest) IsNil() bool { return m == nil }

func (m *JSONRPCRequest) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.JSONRPC)
	w.String("id", m.ID)
	w.String("method", m.Method)
	if m.Params != "" { w.String("params", m.Params) }
}

func (m *JSONRPCRequest) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.JSONRPC = v }
	if v, ok := r.String("id"); ok { m.ID = v }
	if v, ok := r.String("method"); ok { m.Method = v }
	if v, ok := r.String("params"); ok { m.Params = v }
}

type JSONRPCRequestList []*JSONRPCRequest

func (s *JSONRPCRequestList) Schema() []model.Field { return nil }
func (s *JSONRPCRequestList) Pointers() []any     { return nil }
func (s *JSONRPCRequestList) Len() int             { return len(*s) }
func (s *JSONRPCRequestList) At(i int) model.Fielder { return (*s)[i] }
func (s *JSONRPCRequestList) Append() model.Fielder  { v := &JSONRPCRequest{}; *s = append(*s, v); return v }
func (s *JSONRPCRequestList) IsNil() bool          { return s == nil }
func (s *JSONRPCRequestList) EncodeFields(_ model.FieldWriter) {}
func (s *JSONRPCRequestList) DecodeFields(_ model.FieldReader) {}

func (m *JSONRPCNotification) ModelName() string {
	return "jsonrpcnotification"
}

var _schemaJSONRPCNotification = []model.Field{
		{Name: "jsonrpc", Type: model.FieldText},
		{Name: "method", Type: model.FieldText},
		{Name: "params", Type: model.FieldText, OmitEmpty: true},
	}

func (m *JSONRPCNotification) Schema() []model.Field { return _schemaJSONRPCNotification }

func (m *JSONRPCNotification) Pointers() []any { return []any{&m.JSONRPC, &m.Method, &m.Params} }

func (m *JSONRPCNotification) IsNil() bool { return m == nil }

func (m *JSONRPCNotification) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.JSONRPC)
	w.String("method", m.Method)
	if m.Params != "" { w.String("params", m.Params) }
}

func (m *JSONRPCNotification) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.JSONRPC = v }
	if v, ok := r.String("method"); ok { m.Method = v }
	if v, ok := r.String("params"); ok { m.Params = v }
}

type JSONRPCNotificationList []*JSONRPCNotification

func (s *JSONRPCNotificationList) Schema() []model.Field { return nil }
func (s *JSONRPCNotificationList) Pointers() []any     { return nil }
func (s *JSONRPCNotificationList) Len() int             { return len(*s) }
func (s *JSONRPCNotificationList) At(i int) model.Fielder { return (*s)[i] }
func (s *JSONRPCNotificationList) Append() model.Fielder  { v := &JSONRPCNotification{}; *s = append(*s, v); return v }
func (s *JSONRPCNotificationList) IsNil() bool          { return s == nil }
func (s *JSONRPCNotificationList) EncodeFields(_ model.FieldWriter) {}
func (s *JSONRPCNotificationList) DecodeFields(_ model.FieldReader) {}

func (m *JSONRPCResponseStruct) ModelName() string {
	return "jsonrpcresponse_struct"
}

var _schemaJSONRPCResponseStruct = []model.Field{
		{Name: "jsonrpc", Type: model.FieldText},
		{Name: "id", Type: model.FieldText},
		{Name: "result", Type: model.FieldRaw, OmitEmpty: true},
		{Name: "error", Type: model.FieldRaw, OmitEmpty: true},
	}

func (m *JSONRPCResponseStruct) Schema() []model.Field { return _schemaJSONRPCResponseStruct }

func (m *JSONRPCResponseStruct) Pointers() []any { return []any{&m.JSONRPC, &m.ID, &m.Result, &m.Error} }

func (m *JSONRPCResponseStruct) IsNil() bool { return m == nil }

func (m *JSONRPCResponseStruct) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.JSONRPC)
	w.String("id", m.ID)
	if len(m.Result) != 0 { w.Raw("result", m.Result) }
	if len(m.Error) != 0 { w.Raw("error", m.Error) }
}

func (m *JSONRPCResponseStruct) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.JSONRPC = v }
	if v, ok := r.String("id"); ok { m.ID = v }
	if v, ok := r.Raw("result"); ok { m.Result = v }
	if v, ok := r.Raw("error"); ok { m.Error = v }
}

type JSONRPCResponseStructList []*JSONRPCResponseStruct

func (s *JSONRPCResponseStructList) Schema() []model.Field { return nil }
func (s *JSONRPCResponseStructList) Pointers() []any     { return nil }
func (s *JSONRPCResponseStructList) Len() int             { return len(*s) }
func (s *JSONRPCResponseStructList) At(i int) model.Fielder { return (*s)[i] }
func (s *JSONRPCResponseStructList) Append() model.Fielder  { v := &JSONRPCResponseStruct{}; *s = append(*s, v); return v }
func (s *JSONRPCResponseStructList) IsNil() bool          { return s == nil }
func (s *JSONRPCResponseStructList) EncodeFields(_ model.FieldWriter) {}
func (s *JSONRPCResponseStructList) DecodeFields(_ model.FieldReader) {}

func (m *JSONRPCError) ModelName() string {
	return "jsonrpcerror"
}

var _schemaJSONRPCError = []model.Field{
		{Name: "jsonrpc", Type: model.FieldText},
		{Name: "id", Type: model.FieldText},
		{Name: "error", Type: model.FieldRaw},
	}

func (m *JSONRPCError) Schema() []model.Field { return _schemaJSONRPCError }

func (m *JSONRPCError) Pointers() []any { return []any{&m.JSONRPC, &m.ID, &m.Error} }

func (m *JSONRPCError) IsNil() bool { return m == nil }

func (m *JSONRPCError) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.JSONRPC)
	w.String("id", m.ID)
	w.Raw("error", m.Error)
}

func (m *JSONRPCError) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.JSONRPC = v }
	if v, ok := r.String("id"); ok { m.ID = v }
	if v, ok := r.Raw("error"); ok { m.Error = v }
}

type JSONRPCErrorList []*JSONRPCError

func (s *JSONRPCErrorList) Schema() []model.Field { return nil }
func (s *JSONRPCErrorList) Pointers() []any     { return nil }
func (s *JSONRPCErrorList) Len() int             { return len(*s) }
func (s *JSONRPCErrorList) At(i int) model.Fielder { return (*s)[i] }
func (s *JSONRPCErrorList) Append() model.Fielder  { v := &JSONRPCError{}; *s = append(*s, v); return v }
func (s *JSONRPCErrorList) IsNil() bool          { return s == nil }
func (s *JSONRPCErrorList) EncodeFields(_ model.FieldWriter) {}
func (s *JSONRPCErrorList) DecodeFields(_ model.FieldReader) {}

func (m *JSONRPCErrorDetails) ModelName() string {
	return "jsonrpcerror_details"
}

var _schemaJSONRPCErrorDetails = []model.Field{
		{Name: "code", Type: model.FieldInt},
		{Name: "message", Type: model.FieldText},
		{Name: "data", Type: model.FieldText, OmitEmpty: true},
	}

func (m *JSONRPCErrorDetails) Schema() []model.Field { return _schemaJSONRPCErrorDetails }

func (m *JSONRPCErrorDetails) Pointers() []any { return []any{&m.Code, &m.Message, &m.Data} }

func (m *JSONRPCErrorDetails) IsNil() bool { return m == nil }

func (m *JSONRPCErrorDetails) EncodeFields(w model.FieldWriter) {
	w.Int("code", int64(m.Code))
	w.String("message", m.Message)
	if m.Data != "" { w.String("data", m.Data) }
}

func (m *JSONRPCErrorDetails) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("code"); ok { m.Code = int64(v) }
	if v, ok := r.String("message"); ok { m.Message = v }
	if v, ok := r.String("data"); ok { m.Data = v }
}

type JSONRPCErrorDetailsList []*JSONRPCErrorDetails

func (s *JSONRPCErrorDetailsList) Schema() []model.Field { return nil }
func (s *JSONRPCErrorDetailsList) Pointers() []any     { return nil }
func (s *JSONRPCErrorDetailsList) Len() int             { return len(*s) }
func (s *JSONRPCErrorDetailsList) At(i int) model.Fielder { return (*s)[i] }
func (s *JSONRPCErrorDetailsList) Append() model.Fielder  { v := &JSONRPCErrorDetails{}; *s = append(*s, v); return v }
func (s *JSONRPCErrorDetailsList) IsNil() bool          { return s == nil }
func (s *JSONRPCErrorDetailsList) EncodeFields(_ model.FieldWriter) {}
func (s *JSONRPCErrorDetailsList) DecodeFields(_ model.FieldReader) {}

