package mcp

import (
	"github.com/tinywasm/context"
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/json"
)

type Request struct {
	Params callToolParams
}

type Tool struct {
	Name        string
	Description string
	InputSchema string // JSON schema string, generated by ormc
	Resource    string // required — RBAC resource identifier
	Action      byte   // required — 'c','r','u','d'
	Execute     func(ctx *context.Context, req Request) (*Result, error)
}

func (r *Request) Bind(target fmt.SafeFields) error {
	if err := json.Decode([]byte(r.Params.Arguments), target); err != nil {
		return err
	}
	return target.Validate('c')
}

func Text(text string) *Result {
	c := &textContent{Type: "text", Text: text}
	var s string
	_ = json.Encode(c, &s)
	return &Result{Content: s}
}

type FilterFunc func(ctx *context.Context, tool Tool) bool

type ToolProvider interface {
	Tools() []Tool
}
