// DO NOT EDIT. generated by github.com/tinywasm/orm

package mcp_test

import (
	"github.com/tinywasm/fmt"
)

var _schemaactionParams = []fmt.Field{
		{Name: "key", Type: fmt.FieldText},
		{Name: "value", Type: fmt.FieldText},
	}

func (m *actionParams) Schema() []fmt.Field { return _schemaactionParams }

func (m *actionParams) Pointers() []any {
	return []any{
		&m.Key,
		&m.Value,
	}
}

var _schematoolCallParams = []fmt.Field{
		{Name: "name", Type: fmt.FieldText},
	}

func (m *toolCallParams) Schema() []fmt.Field { return _schematoolCallParams }

func (m *toolCallParams) Pointers() []any {
	return []any{
		&m.Name,
	}
}

